#!/bin/bash

# symlink this file to /usr/local/bin/fdb to be able to run it from anywhere
#  ln -s "$(pwd)/fdb" /usr/local/bin/fdb

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

# Run the fdb.cli/-main function with the local fdb dep
clojure -Sdeps "{:deps {org.clojure/clojure {:mvn/version \"1.12.0-alpha5\"} filipesilva/fdb {:local/root \"$SCRIPTPATH\"}}}" -M -m fdb.cli "$@"
